baseURL = "https://ultimates.guide"
languageCode = "en-us"
title = "ultimates.guide"
theme = "tale"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "ultimates.guide"

[params]
  css = [ "/ultimates.guide.css", "/carousel.css" ]

[markup.goldmark.renderer]
unsafe= true

[menu]
  [[menu.main]]
    identifier = "uwu"
    name = "UWU"
    title = "UWU"
    url = "/uwu"
    weight = 0
  [[menu.main]]
    identifier = "ucob"
    name = "UCoB"
    title = "UCoB"
    url = "/ucob"
    weight = 0
